[build]
command = "npx vite build"
publish = "dist"

[functions]
directory = "netlify/functions"
[[redirects]]
  from = "/manifest.json"
  to = "/.netlify/functions/manifest"
  status = 200
[[redirects]]
  from = "/catalog/*"
  to = "/.netlify/functions/catalog"
  status = 200
[build.environment]
SECRETS_SCAN_OMIT_KEYS = "FALLBACK_LANGUAGE,DEFAULT_LANGUAGE,DEFAULT_COUNTRY"